/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Gerenciador;
import estrutura.ArvoreAvl;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Anime;
import model.Filme;
import model.Produtora;
import model.Serie;
/**
 *
 * @author Convidado
 */
public class TelaAdd extends javax.swing.JFrame {
   // private JButton loginTela = new JButton("hoi");
    //JPanel jp = new JPanel();
    //JLabel lb =new JLabel();
    private Gerenciador ger;
    private Anime an;
    private Serie ser;
    private Filme fil;
    private Produtora prod;
    private ArvoreAvl avl;
    private String tipo;
    
    /**
     * Creates new form TelaAdd
     * @param avl
     * @param ger
     */
    public TelaAdd(ArvoreAvl avl, Gerenciador ger) {
        initComponents();
        this.avl = avl;
        this.ger = ger;
        jPEpisode.setVisible(false);
        this.jLGenero1.setVisible(false);
        this.jLGenero2.setVisible(false);
        this.jLGenero3.setVisible(false);
        this.jLGenero4.setVisible(false);
        this.jLGenero5.setVisible(false);
        this.jLGenero6.setVisible(false);
        this.jLGenero7.setVisible(false);
        this.jLGenero8.setVisible(false);
        this.an = new Anime(ger.getAll().size());
        this.fil = new Filme(ger.getAll().size());
        this.ser = new Serie(ger.getAll().size());
        this.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTBPane3 = new javax.swing.JTabbedPane();
        jPanel33 = new javax.swing.JPanel();
        jPNome = new javax.swing.JPanel();
        jTFNome = new javax.swing.JTextField();
        jCBStatus = new javax.swing.JComboBox();
        jPEpisode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFTotalEp = new javax.swing.JTextField();
        jTFAtualEp = new javax.swing.JTextField();
        jCBNota = new javax.swing.JComboBox();
        jLGenero1 = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox();
        jCBGeneros = new javax.swing.JComboBox();
        jLGenero2 = new javax.swing.JLabel();
        jLGenero3 = new javax.swing.JLabel();
        jLGenero4 = new javax.swing.JLabel();
        jLGenero6 = new javax.swing.JLabel();
        jLGenero5 = new javax.swing.JLabel();
        jLGenero8 = new javax.swing.JLabel();
        jLGenero7 = new javax.swing.JLabel();
        jPProdutora = new javax.swing.JPanel();
        jTFProdutora = new javax.swing.JTextField();
        jPComent = new javax.swing.JPanel();
        jTFComent = new javax.swing.JTextField();
        jPData1 = new javax.swing.JPanel();
        jXDate = new org.jdesktop.swingx.JXDatePicker();
        jCBSem = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));

        jPNome.setBackground(new java.awt.Color(255, 255, 255));
        jPNome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome"));

        jTFNome.setBorder(null);

        javax.swing.GroupLayout jPNomeLayout = new javax.swing.GroupLayout(jPNome);
        jPNome.setLayout(jPNomeLayout);
        jPNomeLayout.setHorizontalGroup(
            jPNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFNome)
        );
        jPNomeLayout.setVerticalGroup(
            jPNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jCBStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "Assistindo", "Terminado", "Plano de assistir" }));
        jCBStatus.setToolTipText("");
        jCBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStatusActionPerformed(evt);
            }
        });

        jPEpisode.setBackground(new java.awt.Color(255, 255, 255));
        jPEpisode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPEpisode.setPreferredSize(new java.awt.Dimension(62, 20));

        jLabel1.setText("/");

        jTFTotalEp.setBorder(null);
        jTFTotalEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTotalEpActionPerformed(evt);
            }
        });

        jTFAtualEp.setBorder(null);
        jTFAtualEp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAtualEpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEpisodeLayout = new javax.swing.GroupLayout(jPEpisode);
        jPEpisode.setLayout(jPEpisodeLayout);
        jPEpisodeLayout.setHorizontalGroup(
            jPEpisodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEpisodeLayout.createSequentialGroup()
                .addComponent(jTFAtualEp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTotalEp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPEpisodeLayout.setVerticalGroup(
            jPEpisodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEpisodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jTFTotalEp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTFAtualEp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCBNota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nota", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        jCBNota.setToolTipText("");
        jCBNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNotaActionPerformed(evt);
            }
        });

        jLGenero1.setText("jLabel7");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Serie", "Anime", "Cartoon", "Filme", "Outros" }));
        jCBTipo.setToolTipText("");
        jCBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoActionPerformed(evt);
            }
        });

        jCBGeneros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generos", "Ação", "Animação", "Aventura", "Classico", "Comédia", "Crime", "Drama", "Fantasia", "Ficção Científica", "Guerra", "Mistério", "Suspense", "Horror" }));
        jCBGeneros.setToolTipText("");
        jCBGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGenerosActionPerformed(evt);
            }
        });

        jLGenero2.setText("jLabel7");

        jLGenero3.setText("jLabel7");

        jLGenero4.setText("jLabel7");

        jLGenero6.setText("jLabel7");

        jLGenero5.setText("jLabel7");

        jLGenero8.setText("jLabel7");

        jLGenero7.setText("jLabel7");

        jPProdutora.setBackground(new java.awt.Color(255, 255, 255));
        jPProdutora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produtora"));

        jTFProdutora.setBorder(null);

        javax.swing.GroupLayout jPProdutoraLayout = new javax.swing.GroupLayout(jPProdutora);
        jPProdutora.setLayout(jPProdutoraLayout);
        jPProdutoraLayout.setHorizontalGroup(
            jPProdutoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFProdutora)
        );
        jPProdutoraLayout.setVerticalGroup(
            jPProdutoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPComent.setBackground(new java.awt.Color(255, 255, 255));
        jPComent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Comentario"));

        jTFComent.setBorder(null);

        javax.swing.GroupLayout jPComentLayout = new javax.swing.GroupLayout(jPComent);
        jPComent.setLayout(jPComentLayout);
        jPComentLayout.setHorizontalGroup(
            jPComentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFComent)
        );
        jPComentLayout.setVerticalGroup(
            jPComentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFComent, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPData1.setBackground(new java.awt.Color(255, 255, 255));
        jPData1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data de Lançamento"));

        jXDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPData1Layout = new javax.swing.GroupLayout(jPData1);
        jPData1.setLayout(jPData1Layout);
        jPData1Layout.setHorizontalGroup(
            jPData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPData1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jXDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPData1Layout.setVerticalGroup(
            jPData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPData1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jXDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCBSem.setBackground(new java.awt.Color(255, 255, 255));
        jCBSem.setText("Semanalmente");
        jCBSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPProdutora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(jLGenero5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLGenero6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(jLGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLGenero3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLGenero7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLGenero8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLGenero4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPComent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel33Layout.createSequentialGroup()
                                        .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCBSem))
                                    .addGroup(jPanel33Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jBSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBCancel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPData1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCBNota))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCBSem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPEpisode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGenero1)
                    .addComponent(jLGenero2)
                    .addComponent(jLGenero3)
                    .addComponent(jLGenero4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGenero6)
                    .addComponent(jLGenero5)
                    .addComponent(jLGenero8)
                    .addComponent(jLGenero7))
                .addGap(18, 18, 18)
                .addComponent(jPComent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancel))
                .addContainerGap())
        );

        jTBPane3.addTab("Geral", jPanel33);

        getContentPane().add(jTBPane3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStatusActionPerformed
       String t = String.valueOf(jCBStatus.getSelectedItem());
        switch (t) {
            case "Assistindo":
                jPEpisode.setVisible(true);
                this.an.setEstado(t);
                this.fil.setEstado(t);
                this.ser.setEstado(t);
                break;
            case "Status":
                jPEpisode.setVisible(false);
                this.an.setEstado("Plano de Assistir");
                this.fil.setEstado("Plano de Assistir");
                this.ser.setEstado("Plano de Assistir");
                break;
            default:
                jPEpisode.setVisible(false);
                this.an.setEstado(t);
                this.fil.setEstado(t);
                this.ser.setEstado(t);
                break;
        }
    }//GEN-LAST:event_jCBStatusActionPerformed

    private void jCBNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNotaActionPerformed
        
        int nota;
        nota = Integer.valueOf(String.valueOf(jCBNota.getSelectedItem()));
        this.an.setNota(nota);
    }//GEN-LAST:event_jCBNotaActionPerformed

    private void jTFTotalEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTotalEpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTotalEpActionPerformed

    private void jTFAtualEpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAtualEpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAtualEpActionPerformed

    private void jCBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoActionPerformed
        String s = String.valueOf(jCBTipo.getSelectedItem());
        tipo = s;
    }//GEN-LAST:event_jCBTipoActionPerformed
    private JLabel getFirstJLFree(){
        if(!jLGenero1.isVisible()){
            return jLGenero1;
        }
        else
            if(!jLGenero2.isVisible()){
                return jLGenero2;
            }
        else
            if(!jLGenero3.isVisible()){
                return jLGenero3;
            }
        else
            if(!jLGenero4.isVisible()){
                return jLGenero4;
            }
        else
            if(!jLGenero5.isVisible()){
                return jLGenero5;
            }
        else
            if(!jLGenero6.isVisible()){
                return jLGenero6;
            }
        else
            if(!jLGenero7.isVisible()){
                return jLGenero7;
            }
        else
            if(!jLGenero8.isVisible()){
                return jLGenero8;
            }
        return null;
    }
    private void jCBGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGenerosActionPerformed
       
        String s =String.valueOf(jCBGeneros.getSelectedItem());

        switch (s) {
            case "Ação":
                if(this.getFirstJLFree()!=null){
                    this.getFirstJLFree().setText("Ação");
                    this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                
                break;
            case "Animação":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Animação");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Aventura":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Aventura");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Classico":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Classico");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Comédia":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Comédia");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Crime":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Crime");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Drama":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Drama");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Fantasia":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Fantasia");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Ficção Científica":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Ficção");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Guerra":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Guerra");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Mistério":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Mistério");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Suspense":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Suspense");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
            case "Horror":
                if(this.getFirstJLFree()!=null){
                this.getFirstJLFree().setText("Horror");
                this.getFirstJLFree().setVisible(true);
                    this.an.addGenero(s);
                    this.fil.addGenero(s);
                    this.ser.addGenero(s);
                }
                break;
                                        
        }
    }//GEN-LAST:event_jCBGenerosActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        this.an.setNome(jTFNome.getText());
        this.fil.setNome(jTFNome.getText());
        this.ser.setNome(jTFNome.getText());
        
        this.prod = new Produtora(jTFProdutora.getText());
        this.an.setProd(prod);
        this.ser.setProd(prod);
        this.fil.setProd(prod);
        
        this.an.setObs(jTFComent.getText());
        this.fil.setObs(jTFComent.getText());
        this.ser.setObs(jTFComent.getText());
        
        if(jCBStatus.getSelectedItem().equals("Assistindo")){
            this.an.setEpAtual(Integer.valueOf(jTFAtualEp.getText()));
            this.an.setEpTotal(Integer.valueOf(jTFTotalEp.getText()));
            this.ser.setEpAtual(Integer.valueOf(jTFAtualEp.getText()));
            this.ser.setEpTotal(Integer.valueOf(jTFTotalEp.getText()));
        }
        if(jCBSem.isSelected()){
            SimpleDateFormat sf = new SimpleDateFormat("EEEE");
            String diaSemana = sf.format(jXDate.getDate());
            this.an.setDiaDeLançamento(diaSemana);
            this.ser.setDiaDeLançamento(diaSemana);
        }
        
        switch (tipo){
            case "Serie":
                avl.inserir(this.ser.getId());
                ger.getSeries().add(ser);
                ger.getAll().add(ser);
                break;
            case "Filme":
                avl.inserir(fil.getId());
                ger.getFilmes().add(fil);
                ger.getAll().add(fil);
                break;
            case "Anime":
                avl.inserir(an.getId());
                ger.getAnimes().add(an);
                ger.getAll().add(an);
                break;
        }
        
        JOptionPane.showMessageDialog(null, "Salvo com sucesso!!!", "Sucesso", 1);
        
        for (int i = 0; i < ger.getAll().size(); i++) {
            System.out.println(ger.getAll().get(i));
        }
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jXDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDateActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.an.setDiaDeLançamento(sdf.format(jXDate.getDate()));
    }//GEN-LAST:event_jXDateActionPerformed

    private void jCBSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSemActionPerformed
        
    }//GEN-LAST:event_jCBSemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox jCBGeneros;
    private javax.swing.JComboBox jCBNota;
    private javax.swing.JCheckBox jCBSem;
    private javax.swing.JComboBox jCBStatus;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLGenero1;
    private javax.swing.JLabel jLGenero2;
    private javax.swing.JLabel jLGenero3;
    private javax.swing.JLabel jLGenero4;
    private javax.swing.JLabel jLGenero5;
    private javax.swing.JLabel jLGenero6;
    private javax.swing.JLabel jLGenero7;
    private javax.swing.JLabel jLGenero8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPComent;
    private javax.swing.JPanel jPData1;
    private javax.swing.JPanel jPEpisode;
    private javax.swing.JPanel jPNome;
    private javax.swing.JPanel jPProdutora;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JTabbedPane jTBPane3;
    private javax.swing.JTextField jTFAtualEp;
    private javax.swing.JTextField jTFComent;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFProdutora;
    private javax.swing.JTextField jTFTotalEp;
    private org.jdesktop.swingx.JXDatePicker jXDate;
    // End of variables declaration//GEN-END:variables

}
