/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.exibicao;

import javax.swing.JLabel;
import model.Anime;
import model.Filme;
import model.Serie;

/**
 *
 * @author Convidado
 */
public class ExibirResultado extends javax.swing.JFrame {

    /**
     * Creates new form ExibirResultado
     */
    public ExibirResultado(Anime an) {
        initComponents();
        this.jLID.setText(String.valueOf(an.getId()));
        this.jLNome.setText(an.getNome());
        this.jLOBS1.setText(an.getObs());
        this.jLDatLan1.setText(an.getDiaDeLançamento());
        this.jLDiaSem1.setText(an.getDiaSemanaLançamento());
        this.jLEpA1.setText(String.valueOf(an.getEpAtual()));
        this.jLEpF1.setText(String.valueOf(an.getEpTotal()));
        this.jLRate.setText(String.valueOf(an.getNota()));
        this.jLStatus.setText(an.getEstado());
        this.setFalse();
        this.jLDiaAdd.setText(String.valueOf(an.getAdicionado()));
        for (int i = 0; i < 4 && i < an.getGeneros().size(); i++) {
            this.getFirstJLFree().setText(an.getGeneros().get(i));
        }
        this.setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public ExibirResultado(Serie se) {
        initComponents();
        this.jLID.setText(String.valueOf(se.getId()));
        this.jLNome.setText(se.getNome());
        this.jLOBS1.setText(se.getObs());
        this.jLDatLan1.setText(se.getDiaDeLançamento());
        this.jLDiaSem1.setText(se.getDiaSemanaLançamento());
        this.jLEpA1.setText(String.valueOf(se.getEpAtual()));
        this.jLEpF1.setText(String.valueOf(se.getEpTotal()));
        this.jLRate.setText(String.valueOf(se.getNota()));
        this.jLStatus.setText(se.getEstado());
        this.setFalse();
        this.jLDiaAdd.setText(String.valueOf(se.getAdicionado()));
        for (int i = 0; i < 4 && i < se.getGeneros().size(); i++) {
            this.getFirstJLFree().setText(se.getGeneros().get(i));
        }
        
    }
    public ExibirResultado(Filme fil) {
        initComponents();
        this.jLID.setText(String.valueOf(fil.getId()));
        this.jLNome.setText(fil.getNome());
        this.jLOBS1.setText(fil.getObs());
        this.jLDatLan1.setText(fil.getDiaDeLançamento());
        this.jLDiaSem1.setVisible(false);
        this.jLEpA1.setVisible(false);
        this.jLEpF1.setVerifyInputWhenFocusTarget(false);
        this.jLRate.setText(String.valueOf(fil.getNota()));
        this.jLStatus.setText(fil.getEstado());
        this.setFalse();
        this.jLDiaAdd.setText(String.valueOf(fil.getAdicionado()));
        for (int i = 0; i < 4 && i < fil.getGeneros().size(); i++) {
            this.getFirstJLFree().setText(fil.getGeneros().get(i));
        }
        
    }
    
    private void setFalse(){
        this.jLGen1.setVisible(false);
        this.jLGen2.setVisible(false);
        this.jLGen3.setVisible(false);
        this.jLGen4.setVisible(false);
        this.jLGen5.setVisible(false);
    }
    private JLabel getFirstJLFree(){
        if(!jLGen1.isVisible()){
            return jLGen1;
        }
        else
            if(!jLGen2.isVisible()){
                return jLGen2;
            }
            else
            if(!jLGen2.isVisible()){
                return jLGen2;
            }
            else
            if(!jLGen3.isVisible()){
                return jLGen3;
            }
            else
            if(!jLGen4.isVisible()){
                return jLGen4;
            }
            else
            if(!jLGen5.isVisible()){
                return jLGen5;
            }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLRate = new javax.swing.JLabel();
        jLGeneros = new javax.swing.JLabel();
        jLGen1 = new javax.swing.JLabel();
        jLGen2 = new javax.swing.JLabel();
        jLGen3 = new javax.swing.JLabel();
        jLGen4 = new javax.swing.JLabel();
        jLGen5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLDiaAdd = new javax.swing.JLabel();
        jLEpA = new javax.swing.JLabel();
        jLEpA1 = new javax.swing.JLabel();
        jLEpF = new javax.swing.JLabel();
        jLEpF1 = new javax.swing.JLabel();
        jLDatLan = new javax.swing.JLabel();
        jLDatLan1 = new javax.swing.JLabel();
        jLDiaSem = new javax.swing.JLabel();
        jLDiaSem1 = new javax.swing.JLabel();
        jLOBS = new javax.swing.JLabel();
        jLOBS1 = new javax.swing.JLabel();
        jbAdd1 = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome:");

        jLNome.setText("TAL");

        jLabel3.setText("Status:");

        jLStatus.setText("TAL");

        jLabel5.setText("Nota:");

        jLRate.setText("TAL");

        jLGeneros.setText("Generos:");

        jLGen1.setText("Generos:");

        jLGen2.setText("Generos:");

        jLGen3.setText("Generos:");

        jLGen4.setText("Generos:");

        jLGen5.setText("Generos:");

        jLabel14.setText("ID:");

        jLID.setText("Nome:");

        jLabel16.setText("Adicionado dia:");

        jLDiaAdd.setText("TAL");

        jLEpA.setText("Episodio Atual:");

        jLEpA1.setText("Episodio Atual:");

        jLEpF.setText("Episodio Final:");

        jLEpF1.setText("Episodio Final:");

        jLDatLan.setText("Data de lançamento:");

        jLDatLan1.setText("Data de lançamento:");

        jLDiaSem.setText("Dia da Semana:");

        jLDiaSem1.setText("Dia da Semana:");

        jLOBS.setText("Observação:");

        jLOBS1.setText("Observação:");

        jbAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update32.png"))); // NOI18N
        jbAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLDiaSem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDiaSem1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLOBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLOBS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addComponent(jbAdd1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNome)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLGeneros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLGen1)
                        .addGap(18, 18, 18)
                        .addComponent(jLGen2)
                        .addGap(18, 18, 18)
                        .addComponent(jLGen3)
                        .addGap(18, 18, 18)
                        .addComponent(jLGen4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRate)
                    .addComponent(jLGen5))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDiaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLEpA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEpA1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLEpF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEpF1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLDatLan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDatLan1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLID))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLNome)
                    .addComponent(jLabel3)
                    .addComponent(jLStatus)
                    .addComponent(jLabel5)
                    .addComponent(jLRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLGeneros)
                            .addComponent(jLGen1)
                            .addComponent(jLGen2)
                            .addComponent(jLGen3)
                            .addComponent(jLGen4)
                            .addComponent(jLGen5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLDiaAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLEpA))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEpA1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLEpF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLEpF1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDatLan)
                            .addComponent(jLDatLan1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDiaSem)
                            .addComponent(jLDiaSem1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLOBS)
                            .addComponent(jLOBS1))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdd1ActionPerformed
       
    }//GEN-LAST:event_jbAdd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLDatLan;
    private javax.swing.JLabel jLDatLan1;
    private javax.swing.JLabel jLDiaAdd;
    private javax.swing.JLabel jLDiaSem;
    private javax.swing.JLabel jLDiaSem1;
    private javax.swing.JLabel jLEpA;
    private javax.swing.JLabel jLEpA1;
    private javax.swing.JLabel jLEpF;
    private javax.swing.JLabel jLEpF1;
    private javax.swing.JLabel jLGen1;
    private javax.swing.JLabel jLGen2;
    private javax.swing.JLabel jLGen3;
    private javax.swing.JLabel jLGen4;
    private javax.swing.JLabel jLGen5;
    private javax.swing.JLabel jLGeneros;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLOBS;
    private javax.swing.JLabel jLOBS1;
    private javax.swing.JLabel jLRate;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAdd1;
    // End of variables declaration//GEN-END:variables
}
