/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Main.Control_List;
import Main.Ordena;
import Main.Produto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Convidado
 */
public class Tela1 extends javax.swing.JFrame {
    Control_List cl ;
    Ordena ordena = new Ordena();
    
    public Tela1(Control_List control) {
        this.cl=control;
        initComponents();
        setVisible(true);
    }

    public Tela1() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBnome = new javax.swing.JButton();
        jBpreco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTprods = new javax.swing.JTable();
        jBprintlist = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBid.setText("Id");
        jBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBidActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione um dos campos a serem ordenados:");

        jBnome.setText("Nome");
        jBnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnomeActionPerformed(evt);
            }
        });

        jBpreco.setText("Preço");
        jBpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprecoActionPerformed(evt);
            }
        });

        jTprods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTprods);

        jBprintlist.setText("Imprimir lista");
        jBprintlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprintlistActionPerformed(evt);
            }
        });

        jClear.setText("Limpar Lista");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jAdd.setText("Add produto");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBnome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBpreco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jBprintlist)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBid)
                    .addComponent(jBnome)
                    .addComponent(jBpreco))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBprintlist, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBidActionPerformed
        ordena.porId(cl, 0, cl.getListp().size()-1);


    }//GEN-LAST:event_jBidActionPerformed

    private void jBprintlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprintlistActionPerformed
        int j;
        Produto p = new Produto();
        DefaultTableModel tbm= (DefaultTableModel) jTprods.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        for (int i = 0; i < cl.getListp().size(); i++) {
            j=cl.getListin()[i];
            tbm.addRow(cl.getListp().get(j).getDados());
        }
        
        
    }//GEN-LAST:event_jBprintlistActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        DefaultTableModel tbm= (DefaultTableModel) jTprods.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
    }//GEN-LAST:event_jClearActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        TelaAdd telaAdd = new TelaAdd(cl);
        
    }//GEN-LAST:event_jAddActionPerformed

    private void jBnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnomeActionPerformed
        ordena.porNome(cl, 0, cl.getListp().size()-1);
    }//GEN-LAST:event_jBnomeActionPerformed

    private void jBprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprecoActionPerformed
        ordena.porPreco(cl, 0, cl.getListp().size()-1);
    }//GEN-LAST:event_jBprecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jBid;
    private javax.swing.JButton jBnome;
    private javax.swing.JButton jBpreco;
    private javax.swing.JButton jBprintlist;
    private javax.swing.JButton jClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTprods;
    // End of variables declaration//GEN-END:variables
}
